steps:
- name: 'bash'
  args: ['echo', 'Hello world!']
logsBucket: 'LOGS_BUCKET_LOCATION'
serviceAccount: 'projects/ncert-ai-tutor-2065846720/serviceAccounts/SERVICE_ACCOUNT'
options:
  logging: GCS_ONLY